name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Prepare
    steps:
    -
      name: Checkout release
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - 
      name: Generate version number
      id: version
      run: |
        offset=$(git rev-list origin/master.. --count)
        echo ::set-output name=tag::$offset
      
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - 
      name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - 
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: placeos/driver-spec-runner:${{version.ouputs.tag}}
        labels: |
          org.opencontainers.image.vendor=Place Technology Limited
          org.opencontainers.image.version=${{ version.ouputs.tag }}

    - 
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}