ignored:
  - DL3018 # Allow unpinned packages
  - SC2016 # Ignore single-quotes (expansion not desired)
  - SC1072 # This one seems spurious (related to `for` syntax)
  - DL3016 # No npm version pin on angular builder
  - DL3059 # Consolidation of steps is awkward...
