version: "3.7"

x-deployment-env: &deployment-env
  ENV: ${ENV:-development}
  TZ: $TZ

x-redis-client-env: &redis-client-env
  REDIS_URL: ${REDIS_URL:-redis://redis:6379}

x-build-client-env: &build-client-env
  BUILD_HOST: ${BUILD_HOST:-build}
  BUILD_PORT: ${BUILD_URL:-3000}

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        CRYSTAL_VERSION: ${CRYSTAL_VERSION:-1.1.1}
    volumes:
      - ./spec:/app/spec
      - ./src:/app/src
      - ./.git:/app/.git
      - ./drivers/:/app/drivers/
    depends_on:
      - redis
      - build
    environment:
      # Service Hosts
      << : *redis-client-env
      << : *build-client-env
      # Environment
      << : *deployment-env
      GITHUB_ACTION: ${GITHUB_ACTION:-}

  build:
    image: placeos/build:${PLACE_BUILD_TAG:-nightly}
    restart: always
    hostname: build
    environment:
      TZ: $TZ

  redis:
    image: eqalpha/keydb
    restart: always
    hostname: redis
    environment:
      TZ: $TZ
