version: "3.7"

# YAML Anchors

x-deployment-env: &deployment-env
  ENV: ${ENV:-development}
  SG_ENV: ${SG_ENV:-development}
  TZ: $TZ

x-redis-client-env: &redis-client-env
  REDIS_URL: ${REDIS_URL:-redis://redis:6379}

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        crystal_version: ${CRYSTAL_VERSION:-1.0.0}
    volumes:
      - ./spec:/src/spec
      - ./src:/src/src
      - ./.git:/src/.git
      - ./drivers/:/src/drivers/
      - ./repositories/:/src/repositories/
      - ./lib/:/lib/local-shards/
    depends_on:
      - redis

  redis:
    image: eqalpha/keydb
    restart: always
    hostname: redis
    environment:
      TZ: $TZ