version: "3.7"

x-deployment-env: &deployment-env
  ENV: ${ENV:-development}
  TZ: $TZ

x-redis-client-env: &redis-client-env
  REDIS_URL: ${REDIS_URL:-redis://redis:6379}

x-build-client-env: &build-client-env
  PLACEOS_BUILD_HOST: ${PLACEOS_BUILD_HOST:-build}
  PLACEOS_BUILD_PORT: ${PLACEOS_BUILD_PORT:-3000}

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        CRYSTAL_VERSION: ${CRYSTAL_VERSION:-1.1.1}
    volumes:
      - ${PWD}/spec:/app/spec
      - ${PWD}/src:/app/src
      - ${PWD}/src:/app/local/src
      - ${PWD}/repositories:/app/repositories
      - ${PWD}/.git:/app/repositories/local/.git
      - ${PWD}/shard.yml:/app/repositories/local/shard.yml
      - ${PWD}/shard.lock:/app/repositories/local/shard.lock
      - ${PWD}/drivers:/app/repositories/local/drivers
    depends_on:
      - redis
      - build
    environment:
      # Service Hosts
      << : *redis-client-env
      << : *build-client-env
      # Environment
      << : *deployment-env
      GITHUB_ACTION: ${GITHUB_ACTION:-""}

  build:
    image: placeos/build:${PLACE_BUILD_TAG:-nightly}
    restart: always
    hostname: build
    volumes:
      - ${PWD}/repositories:/app/repositories
      - ${PWD}/src:/app/local/src
      - ${PWD}/.git:/app/repositories/local/.git
      - ${PWD}/shard.yml:/app/repositories/local/shard.yml
      - ${PWD}/shard.lock:/app/repositories/local/shard.lock
      - ${PWD}/drivers:/app/repositories/local/drivers
    environment:
      TZ: $TZ
      PLACEOS_BUILD_LOCAL_BUILDS: "true"

  redis:
    image: eqalpha/keydb
    restart: always
    hostname: redis
    environment:
      TZ: $TZ
