version: "3.7"

x-redis-client-env: &redis-client-env
  REDIS_URL: ${REDIS_URL:-redis://redis:6379}

x-build-client-env: &build-client-env
  PLACEOS_BUILD_HOST: ${PLACEOS_BUILD_HOST:-build}
  PLACEOS_BUILD_PORT: ${PLACEOS_BUILD_PORT:-3000}

volumes:
  repositories:
  drivers:

services:
  test:
    image: placeos/service-spec-runner:${CRYSTAL_VERSION:-1.4.1}
    volumes:
      - ${PWD}/lib:/app/lib:rw
      - ${PWD}/coverage:/app/coverage
      - ${PWD}/shard.lock:/app/shard.lock
      - ${PWD}/shard.override.yml:/app/shard.override.yml
      - ${PWD}/shard.yml:/app/shard.yml
      - ${PWD}/spec:/app/spec
      - ${PWD}/src:/app/src
      - ${PWD}:/app/repositories/local
      - type: volume
        source: repositories
        target: /app/repositories
    depends_on:
      - redis
      - build
    environment:
      # Service Hosts
      << : *redis-client-env
      << : *build-client-env
      # Environment
      GITHUB_ACTION: ${GITHUB_ACTION}

  build:
    image: placeos/build:${PLACE_BUILD_TAG:-nightly}
    restart: always
    hostname: build
    volumes:
      - ${PWD}:/app/repositories/local
      - type: volume
        source: drivers
        target: /app/bin/drivers
      - type: volume
        source: repositories
        target: /app/repositories
    environment:
      PLACEOS_BUILD_LOCAL: "true"
      PLACEOS_ENABLE_TRACE: "true"

  redis:
    image: eqalpha/keydb
    restart: always
    hostname: redis
