ARG crystal_version=1.0.0
FROM crystallang/crystal:${crystal_version}-alpine

WORKDIR /app

# Install the latest version of LibSSH2 and the GDB debugger
RUN apk add --update --no-cache \
  ca-certificates \
  gdb \
  bash \
  iputils \
  libssh2-static \
  yaml-static

RUN apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing watchexec

# Add trusted CAs for communicating with external services
RUN update-ca-certificates

RUN mkdir -p /app/bin/drivers

COPY ./shard.yml /app/shard.yml
COPY ./shard.override.yml /app/shard.override.yml
COPY ./shard.lock /app/shard.lock

RUN shards install --ignore-crystal-version

COPY ./src /app/src
COPY ./spec /app/spec
COPY scripts/* /app/scripts/

CMD /app/scripts/entrypoint.sh
