ARG CRYSTAL_VERSION=1.1.1
FROM crystallang/crystal:${CRYSTAL_VERSION}-alpine

WORKDIR /app

# Install the latest version of LibSSH2 and the GDB debugger
RUN apk add --update --no-cache \
            bash \
            ca-certificates \
            gdb \
            iputils

RUN apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing watchexec

# Add trusted CAs for communicating with external services
RUN update-ca-certificates

RUN mkdir -p /app/bin/drivers

COPY ./shard.yml /app/shard.yml
COPY ./shard.override.yml /app/shard.override.yml
COPY ./shard.lock /app/shard.lock

RUN shards install --ignore-crystal-version

COPY ./src /app/src
COPY ./spec /app/spec
COPY scripts/* /app/scripts/

CMD ["/app/scripts/entrypoint.sh"]
