version: "3.7"

x-redis-client-env: &redis-client-env
  REDIS_URL: ${REDIS_URL:-redis://redis:6379}

x-build-client-env: &build-client-env
  PLACEOS_BUILD_HOST: ${PLACEOS_BUILD_HOST:-build}
  PLACEOS_BUILD_PORT: ${PLACEOS_BUILD_PORT:-3000}

volumes:
  repositories:
  drivers:

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        CRYSTAL_VERSION: ${CRYSTAL_VERSION:-1.1.1}
    volumes:
      - ${PWD}:/app/repositories/local
      - ${PWD}/spec:/app/spec
      - ${PWD}/src:/app/src
      - type: volume
        source: repositories
        target: /app/repositories
    depends_on:
      - redis
      - build
    environment:
      # Service Hosts
      << : *redis-client-env
      << : *build-client-env
      # Environment
      GITHUB_ACTION: ${GITHUB_ACTION}

  build:
    image: placeos/build:${PLACE_BUILD_TAG:-nightly}
    restart: always
    hostname: build
    volumes:
      - ${PWD}:/app/repositories/local
      - type: volume
        source: drivers
        target: /app/bin/drivers
      - type: volume
        source: repositories
        target: /app/repositories
    environment:
      PLACEOS_BUILD_LOCAL: "true"
      PLACEOS_ENABLE_TRACE: "true"

  redis:
    image: eqalpha/keydb
    restart: always
    hostname: redis
