name: Build

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 0 * * 0" # Sunday at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build crystal ${{ matrix.crystal }} image
    strategy:
      fail-fast: false
      matrix:
        crystal:
          - latest
    steps:
      - name: Checkout release
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Set up Docker Cache
      #   uses: actions/cache@v2
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ matrix.crystal }}-${{ github.sha }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64 # ,linux/arm64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          # build-args: |
          #   CRYSTAL_VERSION=${{ matrix.crystal }}
          tags: placeos/drivers-spec:latest
          labels: |
            org.opencontainers.image.vendor=Place Technology Limited
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.title=PlaceOS/driver-spec-runner
