name: CI
on: push
jobs:
  style:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@v2
      - name: Format
        run: crystal tool format --check
      - name: Lint
        uses: crystal-ameba/github-action@v0.2.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: "Test - crystal: ${{ matrix.crystal }}, stable: ${{ matrix.stable }}"
    continue-on-error: ${{ !matrix.stable }}
    strategy:
      fail-fast: false
      matrix:
        stable: [true]
        crystal:
          - 1.0.0
          - 1.1.1
        include:
          - crystal: nightly
            stable: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run docker-compose test environment
      run: ./test
      env:
          CRYSTAL_VERSION: ${{ matrix.crystal }}
