name: CI
on:
  push:
    branches: [ master ]
jobs:
  style:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@v2
      - name: Format
        run: crystal tool format --check
      - name: Lint
        uses: crystal-ameba/github-action@v0.2.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    strategy:
      fail-fast: false
      matrix:
        crystal:
          - latest
          - nightly
          - 1.0.0
    runs-on: ubuntu-latest
    container: crystallang/crystal:${{ matrix.crystal }}
    steps:
    - uses: actions/checkout@v2
    - name: Run docker-compose test environment
      run: ./test
      env:
          CRYSTAL_VERSION: ${{ matrix.crystal }}