name: CI
on: push
jobs:
  crystal-style:
    uses: PlaceOS/.github/.github/workflows/crystal-style.yml@main

  dockerfile-style:
    uses: PlaceOS/.github/.github/workflows/dockerfile-style.yml@main

  test:
    uses: PlaceOS/.github/.github/workflows/containerised-test.yml@main
