name: CI
on:
  push:
  schedule:
    - cron: "0 4 * * 2" # Every Tuesday at 4:00

jobs:
  crystal-style:
    uses: PlaceOS/.github/.github/workflows/crystal-style.yml@main

  dockerfile-style:
    uses: PlaceOS/.github/.github/workflows/dockerfile-style.yml@main

  test:
    uses: PlaceOS/.github/.github/workflows/containerised-test.yml@main
    with:
      cache_shards: false
